export enum NETWORK {
  MAINNET = 1,
  GNOSIS_CHAIN = 100,
  GOERLI = 5,
  ARBITRUM = 42161,
  OPTIMISM = 10,
  POLYGON = 137,
  ZKEVM = 1101,
  AVALANCHE = 43114,
  BSC = 56,
  HARDHAT_NETWORK = 31337,
  LINEA = 59144,
  LINEA_GOERLI = 59140,
  SEPOLIA = 11155111,
  BASE = 8453,
  BASE_SEPOLIA = 84532,
  MANTLE = 5000,
  BERACHAIN = 80094,
  SONIC = 146,
  CELO = 42220,
  BOB = 60808,
  HYPER_EVM = 999,
  WORLD_CHAIN = 480,
  FLARE = 14,
  INK = 57073,
  HEMI = 43111,
  KATANA = 747474,
  LENS = 232,
  PEAQ = 3338,
  UNICHAIN = 130,
  ZKSYNC = 324,
  SCROLL = 534352,
  AURORA = 1313161554,
  GNOSIS_CHIADO = 10200,
}

export interface Coin {
  symbol: string
  decimals: number
}

interface Network {
  chainId: number
  name: string
  shortName: string
  nativeAsset: Coin
}

export const NATIVE_ASSET: Record<string, Coin> = {
  ETH: { symbol: 'ETH', decimals: 18 },
  XDAI: { symbol: 'XDAI', decimals: 18 },
  POL: { symbol: 'POL', decimals: 18 },
  BNB: { symbol: 'BNB', decimals: 18 },
  AVAX: { symbol: 'AVAX', decimals: 18 },
  MNT: { symbol: 'MNT', decimals: 18 },
  S: { symbol: 'S', decimals: 18 },
  BERA: { symbol: 'BERA', decimals: 18 },
  CELO: { symbol: 'CELO', decimals: 18 },
  CORE: { symbol: 'CORE', decimals: 18 },
  FLR: { symbol: 'FLR', decimals: 18 },
  GHO: { symbol: 'GHO', decimals: 18 },
  PEAQ: { symbol: 'PEAQ', decimals: 18 },
  HYPER: { symbol: 'HYPER', decimals: 18 },
}

export const NETWORKS: Record<NETWORK, Network> = {
  [NETWORK.MAINNET]: {
    chainId: NETWORK.MAINNET,
    name: 'mainnet',
    shortName: 'eth',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.GNOSIS_CHAIN]: {
    chainId: NETWORK.GNOSIS_CHAIN,
    name: 'gnosis_chain',
    shortName: 'gno',
    nativeAsset: NATIVE_ASSET.XDAI,
  },
  [NETWORK.GOERLI]: {
    chainId: NETWORK.GOERLI,
    name: 'goerli',
    shortName: 'gor',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.ARBITRUM]: {
    chainId: NETWORK.ARBITRUM,
    name: 'arbitrum',
    shortName: 'arb1',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.OPTIMISM]: {
    chainId: NETWORK.OPTIMISM,
    name: 'optimism',
    shortName: 'oeth',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.POLYGON]: {
    chainId: NETWORK.POLYGON,
    name: 'polygon',
    shortName: 'matic',
    nativeAsset: NATIVE_ASSET.POL,
  },
  [NETWORK.ZKEVM]: {
    chainId: NETWORK.ZKEVM,
    name: 'zkevm',
    shortName: 'zkevm',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.AVALANCHE]: {
    chainId: NETWORK.AVALANCHE,
    name: 'avalanche',
    shortName: 'avax',
    nativeAsset: NATIVE_ASSET.AVAX,
  },
  [NETWORK.BSC]: {
    chainId: NETWORK.BSC,
    name: 'binance_smart_chain',
    shortName: 'bnb',
    nativeAsset: NATIVE_ASSET.BNB,
  },
  [NETWORK.HARDHAT_NETWORK]: {
    chainId: NETWORK.HARDHAT_NETWORK,
    name: 'hardhat',
    shortName: 'hardhat',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.LINEA]: {
    chainId: NETWORK.LINEA,
    name: 'linea',
    shortName: 'linea',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.LINEA_GOERLI]: {
    chainId: NETWORK.LINEA_GOERLI,
    name: 'linea_goerli',
    shortName: 'linea-goerli',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.SEPOLIA]: {
    chainId: NETWORK.SEPOLIA,
    name: 'sepolia',
    shortName: 'sep',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.BASE]: {
    chainId: NETWORK.BASE,
    name: 'base',
    shortName: 'base',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.BASE_SEPOLIA]: {
    chainId: NETWORK.BASE_SEPOLIA,
    name: 'base_sepolia',
    shortName: 'basesep',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.MANTLE]: {
    chainId: NETWORK.MANTLE,
    name: 'mantle',
    shortName: 'mantle',
    nativeAsset: NATIVE_ASSET.MNT,
  },
  [NETWORK.BERACHAIN]: {
    chainId: NETWORK.BERACHAIN,
    name: 'berachain',
    shortName: 'berachain',
    nativeAsset: NATIVE_ASSET.BERA,
  },
  [NETWORK.SONIC]: {
    chainId: NETWORK.SONIC,
    name: 'sonic',
    shortName: 'sonic',
    nativeAsset: NATIVE_ASSET.S,
  },
  [NETWORK.CELO]: {
    chainId: NETWORK.CELO,
    name: 'celo',
    shortName: 'celo',
    nativeAsset: NATIVE_ASSET.CELO,
  },
  [NETWORK.BOB]: {
    chainId: NETWORK.BOB,
    name: 'bob',
    shortName: 'bob',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.HYPER_EVM]: {
    chainId: NETWORK.HYPER_EVM,
    name: 'hyper_evm',
    shortName: 'hyperevm',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.WORLD_CHAIN]: {
    chainId: NETWORK.WORLD_CHAIN,
    name: 'world_chain',
    shortName: 'wc',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.FLARE]: {
    chainId: NETWORK.FLARE,
    name: 'flare',
    shortName: 'flr',
    nativeAsset: NATIVE_ASSET.FLR,
  },
  [NETWORK.INK]: {
    chainId: NETWORK.INK,
    name: 'ink',
    shortName: 'ink',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.HEMI]: {
    chainId: NETWORK.HEMI,
    name: 'hemi',
    shortName: 'hemi',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.KATANA]: {
    chainId: NETWORK.KATANA,
    name: 'katana',
    shortName: 'katana',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.LENS]: {
    chainId: NETWORK.LENS,
    name: 'lens',
    shortName: 'lens',
    nativeAsset: NATIVE_ASSET.GHO,
  },
  [NETWORK.PEAQ]: {
    chainId: NETWORK.PEAQ,
    name: 'peaq',
    shortName: 'PEAQ',
    nativeAsset: NATIVE_ASSET.PEAQ,
  },
  [NETWORK.UNICHAIN]: {
    chainId: NETWORK.UNICHAIN,
    name: 'unichain',
    shortName: 'unichain',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.ZKSYNC]: {
    chainId: NETWORK.ZKSYNC,
    name: 'zksync',
    shortName: 'zksync',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.SCROLL]: {
    chainId: NETWORK.SCROLL,
    name: 'scroll',
    shortName: 'scroll',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.AURORA]: {
    chainId: NETWORK.AURORA,
    name: 'aurora',
    shortName: 'aurora',
    nativeAsset: NATIVE_ASSET.ETH,
  },
  [NETWORK.GNOSIS_CHIADO]: {
    chainId: NETWORK.GNOSIS_CHIADO,
    name: 'gnosis_chiado',
    shortName: 'chi',
    nativeAsset: NATIVE_ASSET.XDAI,
  },
}

export const NETWORK_NATIVE_ASSET: Record<NETWORK, Coin> = {
  [NETWORK.MAINNET]: NATIVE_ASSET.ETH,
  [NETWORK.GNOSIS_CHAIN]: NATIVE_ASSET.XDAI,
  [NETWORK.GOERLI]: NATIVE_ASSET.ETH,
  [NETWORK.ARBITRUM]: NATIVE_ASSET.ETH,
  [NETWORK.OPTIMISM]: NATIVE_ASSET.ETH,
  [NETWORK.POLYGON]: NATIVE_ASSET.POL,
  [NETWORK.ZKEVM]: NATIVE_ASSET.ETH,
  [NETWORK.AVALANCHE]: NATIVE_ASSET.AVAX,
  [NETWORK.BSC]: NATIVE_ASSET.BNB,
  [NETWORK.HARDHAT_NETWORK]: NATIVE_ASSET.ETH,
  [NETWORK.LINEA]: NATIVE_ASSET.ETH,
  [NETWORK.LINEA_GOERLI]: NATIVE_ASSET.ETH,
  [NETWORK.SEPOLIA]: NATIVE_ASSET.ETH,
  [NETWORK.BASE]: NATIVE_ASSET.ETH,
  [NETWORK.BASE_SEPOLIA]: NATIVE_ASSET.ETH,
  [NETWORK.MANTLE]: NATIVE_ASSET.MNT,
  [NETWORK.BERACHAIN]: NATIVE_ASSET.BERA,
  [NETWORK.SONIC]: NATIVE_ASSET.S,
  [NETWORK.CELO]: NATIVE_ASSET.CELO,
  [NETWORK.BOB]: NATIVE_ASSET.ETH,
  [NETWORK.HYPER_EVM]: NATIVE_ASSET.ETH,
  [NETWORK.WORLD_CHAIN]: NATIVE_ASSET.ETH,
  [NETWORK.FLARE]: NATIVE_ASSET.FLR,
  [NETWORK.INK]: NATIVE_ASSET.ETH,
  [NETWORK.HEMI]: NATIVE_ASSET.ETH,
  [NETWORK.KATANA]: NATIVE_ASSET.ETH,
  [NETWORK.LENS]: NATIVE_ASSET.GHO,
  [NETWORK.PEAQ]: NATIVE_ASSET.PEAQ,
  [NETWORK.UNICHAIN]: NATIVE_ASSET.ETH,
  [NETWORK.ZKSYNC]: NATIVE_ASSET.ETH,
  [NETWORK.SCROLL]: NATIVE_ASSET.ETH,
  [NETWORK.AURORA]: NATIVE_ASSET.ETH,
  [NETWORK.GNOSIS_CHIADO]: NATIVE_ASSET.XDAI,
}
